title: FireRick.com
author: FireRick
email: rickdonma@gmail.com
description: A blog dedicated to sharing interesting things in China. If you are curious about China, please feel free to contact me at any time. I am very happy to answer for you.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://firerick.com" # the base hostname & protocol for your site, e.g. http://example.com
# twitter_username: jekyllrb
# github_username:  jekyll

# Build settings
# markdown: kramdown
theme: jekyll-theme-cayman
plugins:
  - jekyll-feed
  - jekyll-sitemap
# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
